name = "mongo-realm-worker"
main = "src/index.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

account_id = "7d3d8945b43413baa391ce4422e5a1e7"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[vars]
ATLAS_APPID = "application-0-evddemn"
ATLAS_TOKEN = "ZDvF79yFwX4hO2DLOJmwi8JML3Uf5R2dmnXn65ABAPq8I5RKagfRz2ZSyZG4wP7s"